# Generated by Django 4.2.6 on 2023-11-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avatarhashtag_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.avatarhashtag'),
        ),
    ]
