# Generated by Django 4.2.6 on 2023-11-11 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_readinglist'),
        ('accounts', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_reading', to='book.book')),
                ('reading_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reading_lists', to='book.readinglist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_reading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userreading',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_readingist'),
        ),
    ]
