# Generated by Django 4.2.6 on 2023-11-13 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_readinglist'),
        ('accounts', '0007_userreading_userreading_unique_readingist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinueReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_continue_reading', to='book.chapter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_continue_reading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='continuereading',
            constraint=models.UniqueConstraint(fields=('user', 'chapter'), name='unique_continuereading'),
        ),
    ]
