# Generated by Django 4.2.6 on 2023-10-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_chapter_chapterimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
    ]
