# Generated by Django 4.2.6 on 2023-10-30 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_chapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chap',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
