# Generated by Django 4.2.6 on 2023-10-30 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_chapter_chap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chap',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
