# Generated by Django 4.2.6 on 2023-11-01 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_chapter_chap'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterimage',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
