# Generated by Django 4.2.6 on 2023-11-04 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book_options_alter_book_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chap',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
