# Generated by Django 4.2.6 on 2023-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_vote_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='mark',
            field=models.IntegerField(choices=[(1, 'BAD'), (2, 'NORMAL'), (10, 'GOOD')]),
        ),
    ]
