# Generated by Django 4.2.6 on 2023-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_rename_view_date_view_date_remove_view_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
