# Generated by Django 4.2.6 on 2023-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_alter_view_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
