# Generated by Django 4.2.6 on 2023-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_alter_vote_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_vote'),
        ),
    ]
