# Generated by Django 4.2.6 on 2023-11-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_vote_unique_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
